# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache mG.bin
      uses: actions/cache@v2
      with:
        path: ~/.EllipticPIR
        key: mG.bin

    - run: npm ci

    - run: npm run build --if-present

    - name: Setup emsdk
      uses: mymindstorm/setup-emsdk@v9
      with:
        version: 2.0.18
        actions-cache-folder: 'emsdk-cache'

    - name: Cache libsodium build directory
      uses: actions/cache@v2
      with:
        path: ${{github.workspace}}/build_em/libsodium-prefix
        key: em_libsodium-prefix

    - name: Build WebAssembly
      run: npm run em:build

    - run: npm test

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: node-${{ matrix.node-version }}
        parallel: true

